import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import styles from "./Layout.module.css";

type Props = {
  children: React.ReactChild;
};

export function Layout({ children }: Props) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  return (
    <div>
      <Head>
        <title>Starlight Counseling</title>
        <meta name="description" content="Generated by create next app" />
        <script type="text/javascript">
          {`bg = new Image(); bg.src="http://starlightcounselingfl.com/beach.jpeg"`}
        </script>
      </Head>
      <header className={styles.header}>
        <span className={styles.headerText}>
          Starlight Counseling and Wellness
        </span>
        <input
          className={styles.menuToggle}
          type="checkbox"
          checked={isMenuOpen}
        />
        <label
          className={styles.menuButtonContainer}
          htmlFor="menu-toggle"
          onClick={() => setIsMenuOpen((s) => !s)}
        >
          <div className={styles.menuButton}></div>
        </label>
        <ul className={styles.menu}>
          <li>
            <Link href="/services">Services</Link>
          </li>
          <li>
            <Link href="/about">About Amanda</Link>
          </li>
        </ul>
      </header>

      {children}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Coffee
        </a>
      </footer>
    </div>
  );
}
